projectName: "wqp-external"
applicationName: "etl-stewards"
dockerImageName: "etl-stewards"
artifactoryPath: "wqp"
gitlabPath: "wma/docker/wqp/etl-stewards"
gitRepoUrl: "https://github.com/NWQMC/etl-stewards"
gitRepoCredentialsId: "Jenkins-GitHub-Read-Write-Token"
memory: 768
rulePriority: 89
contextPath: "/etl-stewards/*"
