spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  datasource-wqp:
    url: jdbc:postgresql://${WQP_DATABASE_ADDRESS}:${WQP_DATABASE_PORT}/${WQP_DATABASE_NAME}
    username: ${WQP_SCHEMA_OWNER_USERNAME}
    password: ${WQP_SCHEMA_OWNER_PASSWORD}
    hikari:
      maximumPoolSize: 10
    initialization-mode: always
  datasource-ars:
      url: jdbc:postgresql://${ARS_DATABASE_ADDRESS}:${ARS_DATABASE_PORT}/${ARS_DATABASE_NAME}
      username: ${ARS_SCHEMA_OWNER_USERNAME}
      password: ${ARS_SCHEMA_OWNER_PASSWORD}
      hikari:
        maximumPoolSize: 10
  liquibase:
    change-log: db/changelog/db.changelog-ars.yaml
    parameters:
      WQP_SCHEMA_NAME: ${WQP_SCHEMA_NAME}
      ETL_OWNER_USERNAME: ${ARS_SCHEMA_OWNER_USERNAME}
